# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddc7e66361dd7fd16f15bc06241b466d3e4d9c5ff7f60a695ccd507f77c8c54b0db5d87639bc4e2b356b6d55316272bcf78c42cb562b5e105c9b38e7e2e4628b

test:
  secret_key_base: 0b77ac203581aa9bd5a6b68e485a38f75ee8a24a3c5c23a74d14877c9d0bba0d1d56dcf5a4e2afa76181e2f3c88a45121858dd3d630736f65da01a3e4a5db318

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
